#oracle configuration
  datasource:
    url: jdbc:oracle:thin:@127.0.0.1:1521/orcl
    username: system
    password: manager
    driver-class-name: oracle.jdbc.OracleDriver

#jpa configuration
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  
